= Project Tetra Docs

This repository contains the content and source code for generating the https://tetrabiodistributed.github.io/project-tetra-docs[Project Tetra Docs] site.

We use https://gohugo.io/[Hugo] and https://asciidoctor.org/[ Asciidoctor] to format and generate our website,
the https://github.com/google/docsy[Docsy] theme for styling and site structure,
https://graphviz.org/[Graphviz] and https://plantuml.com/[plantuml] for rendering diagrams,
and https://github.com/peaceiris/actions-gh-pages[GitHub Actions for GitHub Pages] to manage the deployment of the site.

== Running the website locally

You can run your own Hugo server using docker to preview the site locally:

. Install https://www.docker.com/[docker].
. Clone the https://github.com/tetrabiodistributed/project-tetra-docs[Project Tetra docs repo]. Don't forget to use `--recurse-submodules` or you won't pull down some of the code you need to generate a working site.
+
[source,bash]
----
git clone --recurse-submodules https://github.com/tetrabiodistributed/project-tetra-docs.git
cd project-tetra-docs
----
Note: If you accidentally cloned without using `--recurse-submodules`, you can run `git submodule update --init --recursive` to pull down submodules needed to generate a working site.
. Run the `build.sh` script in the site root directory (Note: Linux users may need to prepend this command `sudo`). This will build a docker image, as well as install node modules, needed to locally run the `project-tetra-docs` Hugo webserver. Once the image is built and stored on your machine, you do not need to rerun this step. You can view all locally installed images by running `docker images`.
+
[source,bash]
----
./build.sh
----
. Run the `serve.sh` script in the site root directory (Note: Linux users may need to prepend this command `sudo`). By default, your site will be available at `+http://localhost:1313/project-tetra-docs+`.
+
[source,bash]
----
./serve.sh
----
. Now that you're serving your site locally, Hugo will watch for changes to the content and automatically refresh your site.

== Contributors

@Burhan-Q Burhan Qaddoumi | Design & Simulation Engineer | Corning, NY, USA

@cyunis Catherine Yunis | Writing, Testing and Assembly | Los Angeles, CA, USA

@chrismolinari456 Christopher Molinari | Documentation, Outreach | Methuen, MA, USA

Daniel Stemen RCP | Clinical Validation and Testing | Los Angeles, CA, USA

Darryl H. Hwang, PhD | Additive Manufacturing and Design Support | Los Angeles, CA, USA

@thehannahfink Hannah Fink | Industrial Design | San Francisco, CA, USA

@Judoguy12 Jamie Waters | Outreach and Project Manager| Worcester, England, UK

John Brooks, MS | Visual Media | Ventura, CA, USA

@jgrano John Grano | Design & Manufacturing Engineer | Denver, CO, USA

Linda Yan | Media | Bellevue, Washington, USA

@mmroden Mark Roden, PhD | Product Manager, Assembly, and Testing | Sherman Oaks, CA, USA

@adebuleo Oluwafemi Adebule | Project Manager | Toronto, ON, Canada

@mechatroniks-git Patrick Campbell | Electromechanical Design Engineer | Los Angeles, CA, USA

@capsulecorplab Sean Marquez | Software & Systems Engineering, Documentation | Los Angeles, CA, USA

@hydronics2 Thomas Hudson | Electromechanical Design Engineer | Portland, OR, USA

Valerie Seabaugh MD | Clinical Advisement and Testing | Los Angeles, CA, USA
