= Project Tetra - Project Repository

This repository contains the content and source code for generating the Project Tetra site.
For more information about Project Tetra, please visit https://tetrabiodistributed.github.io/docs/

This Project is hosted at https://tetrabiodistributed.github.io

== Prerequisites

The following are basic prerequisites for previewing the Project Tetra site on your local machine:

* https://gohugo.io/getting-started/installing/[Install Hugo] for your specific platform.
If you install from the https://github.com/gohugoio/hugo/releases[release page], make sure you download the `_extended` version which supports SCSS.

== Cloning the Project Tetra Project

The following will clone the project repository onto your local machine.
This will allow you to edit and preview changes to the project site (don't forget to use `--recurse-submodules` or you won't pull down some of the code you need to generate a working site).

[source,bash]
----
git clone --recurse-submodules --depth 1 https://github.com/tetrabiodistributed/tetrabiodistributed.github.io.git
cd project-tetra
----

== Running the website locally

Once you've cloned the project repo, from the `tetrabiodistributed.github.io` root directory, run:

[source,bash]
----
sh serve.sh
----

The `serve.sh` script builds and locally serves the site to https://localhost:1313.
