
---
title: "Explanation"
linkTitle: "Explanation"
weight: 1
description: >
  Background on Tetra's rationale and approach to Open-Source Hardware (OSHW) development process for medical devices
---

== Why did Tetra adopt an open-source model for developing medical devices?

footnote:[https://makezine.com/2020/09/21/the-pandemic-inspired-case-for-an-open-source-medical-hardware-ecosystem/]

== What is Open-Source Hardware (OSHW)? ==

Open Source Hardware (OSHW) is a term for tangible artifacts — machines, devices, or other physical things — whose design has been released to the public in such a way that anyone can make, modify, distribute, and use those things. This definition is based on the http://opensource.org/docs/osda[Open Source Definition] for Open Source Software and is intended to help provide guidelines for the development and evaluation of licenses for Open Source Hardware. See https://www.oshwa.org/definition/[Open Source Hardware (OSHW) Definition]

== What is _Docs as Code_? ==

Tetra follows a _docs as code_ approach to developing Open-Source Hardware (OSHW) for medical devices.

Documentation as Code (_Docs as Code_) refers to a philosophy that you should be writing documentation with the same tools as code. See https://capsulecorplab.github.io/docs-as-code/[An Intro to Docs as Code].

=== Languages ===

The site is generated from a combination of the https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc markup language] and https://gohugo.io/templates/introduction/[Hugo template language]. Asciidoc is a markup language that was designed specifically for technical writing and documentation.

=== Tools ===

We use https://gohugo.io/[Hugo] and https://asciidoctor.org/[Asciidoctor] to format and generate our website,
the https://github.com/google/docsy[Docsy] theme for styling and site structure,
https://graphviz.org/[Graphviz] and https://plantuml.com/[PlantUML] for rendering diagrams,
and https://github.com/peaceiris/actions-gh-pages[GitHub Actions for GitHub Pages] to manage the deployment of the site.
Hugo is an open-source static site generator that provides us with templates,
content organisation in a standard directory structure, and a website generation engine.
You write the pages in AsciiDoc (or HTML if you want), and Hugo wraps them up into a website.

=== Methodologies ===

We use a https://www.writethedocs.org/guide/docs-as-code/[Docs as Code] (i.e., __maintain documentation using the same tools used to maintain code__) with https://www.writethedocs.org/videos/portland/2019/lessons-learned-in-a-year-of-docs-driven-development-jessica-parsons/[Documentation Driven Development] (i.e., __Document first, then implement what you documented__) approach, using the GitHub workflow, to facilitate documentation for Tetra Bio Distributed. Content is organized using https://documentation.divio.com/[The Documentation System]. The documentation for this project is maintained in the https://github.com/tetrabiodistributed/project-tetra-docs[Tetra Bio Distributed docs repo] with the project source code maintained in the https://github.com/tetrabiodistributed/project-tetra[Tetra Bio Distributed repo].
