

@startuml

skinparam nodesep 100

skinparam ranksep 100

frame "Electronic Sensing System" {

[Raspberry Pi B+] <<Microcontroller>> as [Pi]

rectangle "Power System" {

    [LM259SX-5] <<Voltage Regulator>> as [VR]

    [Power Jack] as PJ

    () "Wall Outlet" as WO

}

rectangle "Clinical Feedback" {

    () "Raspberry Pi B+ Display" <<Display>> as Display

    () "Indicator LEDs (x8)" as LED

    () "Audio Alarm"  as Aud

}

'Already on board'

{

rectangle "Pressure Sensing System" as PresSens{

    [BME280 (x5)] <<Pressure Sensors>> as Pres 

    [TCA9548A] <<I2C Pressure Multiplexer>> as [MUX1]

    () "Pressure Sensor Connectors" as PCon 

    Pres .left.> PCon

    PCon .left.> MUX1

}

rectangle "Open-Source Flow Sensing System"  as Open{

    [Automotive Airflow Sensors (x4)] <<Generic Sensors>> as AAS 

    [TCA9548A] <<Analog Digital Converter>> as [ADC]

    () "Automotive Airflow Connectors" as ACon 

    AAS .left.> ACon

    ACon .left.> ADC

}

rectangle "FDA-Approved Flow Sensing System"  as FDA{

    [Sensiron Airflow Sensors (x4)] <<Sensiron Sensors>> as Sens

    [TCA9548A] <<I2C Flow Multiplexer>> as [MUX2]

    () "Sensiron Airflow Connectors" as SCon

    Sens .left.> SCon

    SCon .left.> MUX2

}

}

PresSens -[hidden]-> FDA 

'Used for aligning boxes'

FDA -[hidden]-> Open

"Clinician" <<Human>> as Doc

"Patient" <<Human>> as Pat

Sens <-right- Pat

AAS <-right- Pat

Pres <-right- Pat

WO <-down- PJ

PJ <-down- VR

VR <-down- Pi

Pi <.left. MUX1

Pi <.left. MUX2

Pi <.left. ADC

Pi <.down. LED

Pi <.down. Aud

Pi <.down. Display

LED <.down. Doc

Aud <.down. Doc

Display <.down. Doc

}

@enduml

