@startuml
left to right direction
skinparam linetype polyline
/'
skinparam linetype ortho
'/

frame "ibd [System] Ventilator Splitter Assembly [Air flow] " {

  actor "<b>patient</b>" <<human>> as patient

  component "<b>LTV-1200</b>" <<ventilator>> as ventilator {
    interface "<b>Expiratory Port</b>" as pOut
    interface "<b>Inspiratory Port</b>" as pIn
  }

  component "<b>Inspiratory Arm P/N</b>" <<Inspiratory Arm>> as armIn
  component "<b>Expiratory Arm P/N</b>" <<Expiratory Arm>> as armOut

  pOut <.. armOut
  pIn ..> armIn

  component "<b>Ventilator Splitter Assembly</b>" <<block>> as vsb {
    component "<b>Inspiratory Section</b>" <<block>> as vsbIn
    component "<b>Expiratory Section</b>" <<block>> as vsbOut
    interface "<b>Inspiratory Port</b>" as vsbpIn
    interface "<b>Expiratory Port</b>" as vsbpOut

    component "<b>Bias Circuit P/N</b>" <<bias circuit>> as bc

    vsbpOut -- vsbOut
    vsbpIn -- vsbIn
    vsbOut <. bc
    bc <. vsbIn

    component "<b>1-Way Valve P/N</b>" <<1-Way valve>> as vIn1
    component "<b>Flow Control P/N</b>" <<flow control>> as fcIn1
    component "<b>Shutoff valve P/N</b>" <<shutoff valve>> as sIn1

    vsbIn ...> vIn1
    vIn1 ..> fcIn1
    fcIn1 ..> sIn1

    component "<b>1-Way Valve P/N</b>" <<1-Way valve>> as vOut1
    component "<b>Pressure sensor P/N</b>" <<pressure sensor>> as psOut1
    component "<b>Shutoff valve P/N</b>" <<shutoff valve>> as sOut1

    vsbOut <... vOut1
    vOut1 <.. psOut1
    psOut1 <.. sOut1
  }

  armIn ..> vsbpIn
  armOut <.. vsbpOut

  component "<b>Inspiratory Arm to patient P/N</b>" <<Inspiratory Arm>> as arm2patIn
  component "<b>Expiratory Arm to patient P/N</b>" <<Expiratory Arm>> as arm2patOut

  sIn1 ..> arm2patIn
  arm2patIn ..> patient

  sOut1 <.. arm2patOut
  arm2patOut <.. patient
}
@enduml
