
---
title: "How to build a PAPR"
linkTitle: "How to build a PAPR"
weight: 1
description: >
  Describes how to build a PAPR.
---

== Quick Synopsis

This guide will walk you through how to build a PAPR.  It assumes that you have some knowledge of soldering, 3D-printing, and cutting foam with a knife using a stencil, or that you're willing to learn, as the steps are fairly bsaic.  In the end, you will have three things: a box with a filter and a fan in it, a second box with batteries and a fan controller, and a mask.  These three things will be connected by hoses, wires, and straps, and you'll have something that will protect you and those around you from breathing COVID-19 or any other airborne virus transmitted through breathing, coughing, etc.  

Please note that this system will not protect you from anything landing in your eyes.  For that protection, either the mask will need to be modified to be a helmet, or you will need a face shield.

== Introduction

Now, in the time of COVID-19, many people are at risk for exposure to the virus and cannot afford to get infected.  These people can isolate themselves, but often, their professions or requirements for daily life will take them in contact with other people, and they need some form of protection.  Masks definitely help, but can become uncomfortable to wear, and also obscure the face of the wearer.  This guide will walk you through creating a Powered Air-Purifying Respirator, which will protect the wearer and those around them from airborne viruses and bacteria, while at the same time providing positive airflow to the wearer's face.  That airflow makes sure that the wearer has a supply of fresh, cooled, clean air that has gone through a filtration process, and, in our tests, is the equivalent of wearing an N99 mask.

The core of the idea is fairly simple: put a fan behind a filter in an airtight box, have the fan pull air through the filter, and push that air through a hose.  The hose goes to a mask on the wearer's face.  The wearer then breathes out, and air travels through a second hose back into the box and back out through the same filter.  This system means that the wearer only needs one filter for both inhalation and exhalation.  The wearer is protected from their surroundings, and anyone in the surroundings is protected from the wearer, both by the same filter.  The filter itself lasts for 3 months or so, while the battery is rechargeable for repeated use.

== 3D Printed Parts

You will need to print, using an FDM printer, PLA resin, at 0.2mm spacing:

1.  The fan box bottom half (holds the fan)
2.  The fan box top half (holds the filter)
3.  The fan box funnel that takes air from the fan into the hose
4.  The fan box grill that holds the filter in place
5.  The battery case to hold the battery and fan control board
6.  The battery plate to protect the fan control board
7.  The face mask
8.  Four spacers

== Bill Of Materials

You will need to buy these parts  (prices fluctuate, so are not included here):

.Table Title
|===
| Count | Description | URL | Number in Package 

| 1 
| Onyehn DC Motor PWM Speed Controller3V 6V 12V 24V 35V Speed Control Switch Mini LED Dimmer 5A 90W	 
| https://www.amazon.com/gp/product/B07GP72BWV/ 
| 2 

| 1	
| UTUO Brushless Radial Blower Dual Ball Bearing High Speed 12V DC Centrifugal Fan with XH-2.5 Plug 120mm by 120mm by 32mm 4.72x4.72x1.26 inch	
| https://www.amazon.com/gp/product/B01CSNEO2G/ 
| 1	

| 1	
| 2Pack Upgraded 3.5Ah M 12 Battery for Milwaukee 12V Battery Lithium XC M 12B Batteries 
| https://www.amazon.com/gp/product/B082WW688D/	
| 2	

| 2	
| Baomain Male Spade Quick Splice Crimp Terminals 6.3mm Crimp Connector Non Insulated	
| https://www.amazon.com/gp/product/B01MQ332R6/ 
| 	100	

| 1	
| Guardian Technologies FLT4010 Genuine High-Performance Allergen Air Purifier Replacement Filter A With Activated Charcoal Layer 
| https://www.amazon.com/gp/product/B003AKNK4A/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1	
| 1	

| 2	
| TOTOT 30 Pack 5.5mm x 2.1mm 3 Pin Female DC Power Jack Panel Mount Screw Nut Kit DC Socket Electrical Plug 
| https://www.amazon.com/gp/product/B077YC457J/ 
| 	30	

| 1	
| Donner 60CM Guitar Pedal Power Cable Cord 10-Pack 
| 	https://www.amazon.com/gp/product/B078XRM3W4/ 
| 10	

| 8	
| binifiMux 150pcs M4 x 0.7mm 304 Stainless Steel Hex Nuts Bright Finish 
| https://www.amazon.com/gp/product/B07J6C1XTD/ 
| 150	

| 8	
| 50 Pcs M4-0.70 x 20mm Button Head Socket Cap Bolts Screws, 18-8 Stainless Steel, Allen Hex Drive, ISO 7380, by Fullerkreg,Come in a Plastic Case 
| https://www.amazon.com/M4-0-7X-Available-Stainless-Machine-Fastener/dp/B081JYXLK7/ 
| 	50	 

| 6	
| BNTECHGO 20 Gauge Silicone wire 10 ft red and 10 ft black Flexible 20 AWG Stranded Copper Wire 
| https://www.amazon.com/gp/product/B01AAX64EC/ 
| 120	 

| 6"	
| 20 awg Solid wire kit Electrical wire Cable 7 colors 23ft each spools 20 gauge UL1007 Tinned Copper Hook up wire kit breadboard wire for DIY 
| https://www.amazon.com/Electrical-colors-spools-UL1007-breadboard/dp/B083DNGSPV/ 
| 	276	 

|
| Foam 
| 
| 

|  
| Weather stripping 
| 
|

|
| Dryer Tape 
| 
| 

|  
| Webbing/Straps
| 
|

|
| CPAP Hoses 
| 
| 
|===


== Necessary Tools

You will need these tools:

1.  A crimper
2.  Needlenose pliers
3.  A soldering iron
4.  A hex screwdriver for the m4 screws
5.  Tin snips
6.  An x-acto knife
7.  A 3D printer capable of printing all of the listed components (note the size of the print bed for the fan box)

== Building the Battery/Controller Box


== Building the Fan Box


== Attaching to the Mask


== Care and Maintenance

Filter swaps every 3 months

Battery charge as necessary

Cleaning the exhalation line of condensed water

== Alternative designs

You can create a version of this with no egress tube, but instead have an egress one-way valve on the mask.  This approach will mean that those around you are not protected, but avoids the problem of water building up in the exhalation line.

You can create a design using a mask fitment device, as in this guide: <guide>  However, you will compromise your mask, and that may mean less protection for you.  You will also have to replace the mask as frequently as if you did not have your PAPR in place.

For both of these designs, the dual funnel from the fan box can be replaced with a single-funnel variant.

