---
title: "How to build a Tetra PAPRa m12 Battery Controller (v2)"
linkTitle: "How to build a Tetra PAPRa m12 Battery Controller (v2)"
weight: 1
description: >
  Describes how to build the January 2021 version of the Tetra PAPRa m12 battery controller component.
---

== Quick Synopsis

The Tetra Powered Air Purified Respirator requires power to function, and the m12 battery controller provides that power for these models.  The controller consists of internal circuitry, a potentiometer to adjust fan speeds, a cable to connect to the fan box, and a port for a Milwaulkee M12 Battery to be inserted.

This build differs from the v1 version in that it uses a custom-built circuitboard to remove many of the difficult steps of the build, add a battery charge indicator, and a separate power port for use in a car.  If you cannot get the custom board (found in this repository: https://github.com/tetrabiodistributed/tetra-papr-electronics), then please refer to the v1 version of this guide.

== Parts Required

This build will require printed parts, purchased parts, and several tools.

## 3D Printed Parts

These parts should be printed at 0.2 spacing:

.Table Printed Parts
|===
| Part | Quantity | Material | Supports Required? STL File Location

| The Body
| 1 
| PLA
| No
| https://github.com/tetrabiodistributed/papr-print-files/blob/069ee8212b07bd58bc4ea83722a825267ecaf0e5/STLs/M12%20Controller%20Body.stl

| The Lid
| 1 
| PLA
| No
| https://github.com/tetrabiodistributed/papr-print-files/blob/069ee8212b07bd58bc4ea83722a825267ecaf0e5/STLs/M12%20Controller%20Lid.stl

| The Plate
| 1 
| PLA
| No
| https://github.com/tetrabiodistributed/papr-print-files/blob/069ee8212b07bd58bc4ea83722a825267ecaf0e5/STLs/M12%20Controller%20Plate.stl

